name: "Docker publish"
description: "Build and pushes images"
inputs:
  targets:
    description: "List of bake targets"
    required: false
  registry:
    default: ghcr.io
    description: "Docker registry"
    required: true
  registryUsername:
    default: ${{ github.actor }}
    description: "Docker registry username"
    required: true
  registryPassword:
    default: ${{ github.token }}
    description: "Docker registry password"
    required: true
runs:
  using: "composite"
  steps:
    - id: gitversion
      uses: SoftSimConsult/actions/gitversion@main
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registryUsername }}
        password: ${{ inputs.registryPassword }}
    - name: Build and push
      uses: docker/bake-action@master
      env:
        REGISTRY: ${{ inputs.registry }}
      with:
        push: true
        targets: ${{ inputs.targets }}
